### ISSUE TITLE
Invalid uri in nuget package's project url

### ISSUE THREAD

**Issue by rasmus-s** [projectgoav/E.Deezer#40]
Hi @projectgoav 
Your nuget package has a invalid projectUrl which cause a error in VS 2015.  Error: [nuget.org] Error converting value "http:///github.com/projectgoav/E.Deezer" to type 'System.Uri'. Path 'projectUrl', line 1, position 531.

You have 3 '/' after http:

Hope you will fix it asap.

--
Rasmus

**Comment by projectgoav** [comment]
Believe that should be fixed now! :)

**Comment by rasmus-s** [comment]
Hi @projectgoav 
Its not fixed for all releases.
Will you please change the  2 individual releases (v. 1.1.0.117 and v. 1.0.0.96) which still had the invalid url.

You can see the list of all releases here: https://api.nuget.org/v3/registration0/e.deezer/index.json 
and there is 2 releases of E.Deezer with wrong projectUrl. And nuget manager in Visual Studio read them all when you install a package, and its fail to install self the latest version.

**Comment by projectgoav** [comment]
Hi there,

Didn't realise that "Save" only saved the changes for a single version and not on all version. Think it should be fixed this time! Not sure how long until the changes will take affect.

**Comment by rasmus-s** [comment]
I can confirm that its now working from VS. Without any clear cache etc. commands/hacks
